<SimpleVisu>:
	BoxLayout:
		width: 500
		Button:
			text: "Reset Safety"
			on_press: root.reset_safety()
		Button:
			text: "move array"
			on_press: root.move_array()
		Button:
			text: "build Bahn from PC!"
			on_press: root.build(4)
		Button:
			text: "build Bahn1!"
			on_press: root.build(1)
		Button:
			text: "build Bahn2!"
			on_press: root.build(2)
		Button:
			text: "build Bahn3!"
			on_press: root.build(3)
		Button:
			text: "build Bahn Lager!"
			on_press: root.build(0)